### ISSUE TITLE
shadow or drop-shadow wont work on Android or iOS

### ISSUE THREAD

**Issue by crazywako** [marklawlor/nativewind#130]
**Describe the bug**
`shadow` or `drop-shadow` classNames wont work on Android or iOS

**To Reproduce**
https://snack.expo.dev/R_A2j2wZ5

![image](https://user-images.githubusercontent.com/1356391/180667020-83012b6c-5b2c-4536-ad9f-f01f519bc195.png)

**Comment by anymore1405** [comment]
@crazywako try https://www.nativewind.dev/quick-starts/expo. In snack i saw you not installed tailwindcss in dev dependencies yet

**Comment by marklawlor** [comment]
The snacks cannot install tailwind due to its use of the `crypto` module for hashing. The snacks instead use an external compiler.

While strangely intermittent, I can reproduce the issue. I know how to fix the issue, but I want to do some internal refactoring to cleanly handle android/ios style props.

**Comment by marklawlor** [comment]
This should be fixed on `latest`, let me know if you have any issues. Like with RN shadow, the `shadow` utilities don't always work if a background color is not set.

**Comment by jpmadrigal07** [comment]
@marklawlor `shadow` is still not working

![image](https://user-images.githubusercontent.com/20082606/188256163-2eb181ba-14db-449b-a201-6f4f131a0ecc.png)

**Comment by marklawlor** [comment]
Tailwind `shadow` refers to a box shadow. React Native `<Text>` elements do not support box shadows, only text shadows. TailwindCSS doesn't have a utility  class for the CSS prop `text-shadow` so there's no current way to apply a shadow to text. I'm thinking of adding custom classes to NativeWind based upon this package https://www.npmjs.com/package/tailwindcss-textshadow

Tailwind also has a drop-shadow utility, but there is no native equivalent.

As for the shadow on the view, can you try adding the shadow via inline styles. RN shadows are very buggy and often it's easier to make them work via inline styles and then convert that to Tailwind. If you can make it work with inline styles but not Tailwind, can you please link me an Expo snack demonstrating it.

**Comment by a-eid** [comment]
@marklawlor not sure what the issue is with RN View Shadows, they are different on ios  and android but they work.

it would be nice if you make something similar to 'react-native-zephyr', it's not perfect but it works for now.

**Comment by luizov** [comment]
Had a similar issue, in spite of 'shadow' being set to a View component (not Text). What fixes it is to always add a shadow color after, for example: `shadow-lg shadow-black/40`.

**Comment by jeystaats** [comment]
> shadow-lg shadow-black/40

Yeah had the same, adding the default style for the react-native element worked even better

```
<Pressable
  style={{
    shadowColor: "#000",
  }}
  className="bg-fuchsia-400 h-auto rounded-lg shadow-xl w-full"
  onPress={() => console.log("press")}
>
  <Text className="p-4 text-white font-bold text-md text-center">
    Button
  </Text>
</Pressable>
```

**Comment by Heracraft** [comment]
Had the same problem, fixed it by using @jeystaats solution but using a tailwind class `shadow-black`

`<View className="p-3 rounded-full shadow- shadow-black"></View>`
