### ISSUE TITLE
instet-0 is not working on expo 49

### ISSUE THREAD

**Issue by rohankm** [marklawlor/nativewind#493]
Hi,
My app was working perfectly on expo 48 but when I updated it to expo 49 the :`inset-0` was not working. i had to replace with `w-full h-full`. Hope we will get a fix for this soon.

**Comment by JClackett** [comment]
I also just upgraded and now the dark mode classes dont work e.g text-black dark:text-white

**Comment by Antonio-Sitoe** [comment]
I have the same issues, iam develop my app in expo 49.

**Comment by hayata-suenaga** [comment]
I also have the same issue

**Comment by marklawlor** [comment]
These issues should be fixed with Expo SDK 50 and NativeWind v4, please open a new issue if your experiencing any issues

**Comment by huynq1175** [comment]
I have the same issues in RN 0.74.2

**Comment by martinezguillaume** [comment]
Still not working on nativewind 4.0.36 & react-native 0.74.2
